1,$ s/temperature/Temp/g
1,$ s/index/Idx/g
1,$ s/Level/Lvl/g
1,$ s/1000/OneK/g
1,$ s/virtual/VR/g
1,$ s/Station/Stat/g
1,$ s/Condensation/Cond/g
1,$ s/Convective/Conv/g
1,$ s/Available/Avail/g
1,$ s/Precipitable/Precip/g
1,$ s/water/H20/g
